import { Toaster } from '@/components/ui/sonner';
import { cn } from '@/utils/cn';
import type { Metadata } from 'next';
import { Kumbh_Sans } from 'next/font/google';
import ReduxProvider from '../providers/ReduxProvider';
import ThemeProvider from '../providers/ThemeProvider';
import '../styles/globals.css';

const kumbhSans = Kumbh_Sans({
  variable: '--font-kumbh-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: {
    absolute: '',
    default: 'Your Capture Awards',
    template: '%s | Your Capture Awards',
  },
  description: 'Generated by create next app',
  icons: {
    // icon: [
    //   {
    //     media: '(prefers-color-scheme: light)',
    //     url: '/site-icon.png',
    //     href: '/site-icon.png',
    //   },
    //   {
    //     media: '(prefers-color-scheme: dark)',
    //     url: '/site-icon.png',
    //     href: '/site-icon.png',
    //   },
    // ],
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={cn(
          'bg-background text-foreground antialiased',
          kumbhSans.className,
          kumbhSans.variable,
        )}
      >
        <ThemeProvider>
          <ReduxProvider>
            {children}{' '}
            <Toaster
              expand
              richColors
              position="bottom-right"
              swipeDirections={['bottom', 'left', 'right', 'top']}
              duration={3000}
            />
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
