import type { Metadata } from 'next';
import { Geist, Geist_Mono, Kumbh_Sans } from 'next/font/google';
import '../styles/globals.css';
import { Toaster } from 'sonner';
import Providers from './providers';
import { getUser } from '@/lib/server/getUser';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const kumbhSans = Kumbh_Sans({
  variable: '--font-kumbh-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: {
    absolute: '',
    default: 'Your Capture Awards',
    template: '%s | Your Capture Awards',
  },
  description: 'Generated by create next app',
  icons: {
    icon: [
      {
        media: '(prefers-color-scheme: light)',
        url: '/site-icon.png',
        href: '/site-icon.png',
      },
      {
        media: '(prefers-color-scheme: dark)',
        url: '/site-icon.png',
        href: '/site-icon.png',
      },
    ],
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await getUser();

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} ${kumbhSans.variable} anti-aliased`}
      >
        <Providers user={data?.user} token={data?.token}>
          {children} <Toaster expand={true} richColors closeButton />
        </Providers>
      </body>
    </html>
  );
}
